name: CI/CD

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
    build:
        name: Build and publish
        runs-on: ubuntu-latest
        outputs:
            docker-version: ${{ steps.gitversion.outputs.shortSha }}
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v3.0.3
            - name: Determine version
              id: gitversion
              uses: gittools/actions/gitversion/execute@v3.0.3
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v3.7.1
            - name: Azure login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Publish image
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                  az acr build --registry acrwebrioglobal --image tfalise/webrio:${{ steps.gitversion.outputs.shortSha }} --file src/app/Dockerfile src/app/
    deploy-dev:
      name: Deploy to dev
      needs: build
      uses: ./.github/workflows/deploy.yml
      with:
        environment: dev
        version: ${{ needs.build.outputs.docker-version }}
      secrets: inherit